spring.application.name=Commuto Backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/commuto_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
logging.level.org.springframework.security=DEBUG